import {FunctionComponent, ReactNode} from 'react'
import styles from "../styles/Home.module.css"
import Head from 'next/head'

const Layout: FunctionComponent<{children: ReactNode[]}> = ({children}) => {
    return (
        <div className={`${styles.container} ${styles.lightTheme}`}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
          <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        </Head>
        <div className={styles.heroMain}>
        <head>

        </head>
        </div>
        {children}
        </div>
    )
}


export default Layout
